apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-server
spec:
  secretName: test-server-tls
  isCA: false
  usages:
    - server auth
    - client auth
  dnsNames:
  - "test-server.test.svc.cluster.local"
  - "test-server"
  issuerRef:
    name: selfsigned
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-client
spec:
  secretName: test-client-tls
  isCA: false
  usages:
    - server auth
    - client auth
  dnsNames:
  - "test-client.test.svc.cluster.local"
  - "test-client"
  issuerRef:
    name: selfsigned
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: c
spec:
  secretName: c-tls
  isCA: false
  usages:
    - server auth
    - client auth
  dnsNames:
  - "c.tensotha.local"
  issuerRef:
    name: selfsigned